#pragma once
// AUTO-GENERATED by tools/convert_cat_assets.py — do not edit by hand.
#include <Arduino.h>

#define CAT_FRAME_W 32
#define CAT_FRAME_H 32

struct CatFrame {
    const uint16_t* pixels; // RGB565, row-major, PROGMEM
    const uint8_t*  mask;   // 1=draw, 0=transparent, PROGMEM
    uint16_t        width;
    uint16_t        height;
};

extern const CatFrame CAT_FRAME_TEST_0;
extern const CatFrame CAT_FRAME_TEST_1;
extern const CatFrame CAT_FRAME_TEST_2;
extern const CatFrame CAT_FRAME_TEST_3;
extern const CatFrame CAT_FRAME_WALK_RIGHT_0;
extern const CatFrame CAT_FRAME_WALK_RIGHT_1;
extern const CatFrame CAT_FRAME_WALK_RIGHT_2;
extern const CatFrame CAT_FRAME_WALK_RIGHT_3;
extern const CatFrame CAT_FRAME_WALK_LEFT_0;
extern const CatFrame CAT_FRAME_WALK_LEFT_1;
extern const CatFrame CAT_FRAME_WALK_LEFT_2;
extern const CatFrame CAT_FRAME_WALK_LEFT_3;
extern const CatFrame CAT_FRAME_WALK_DOWN_0;
extern const CatFrame CAT_FRAME_WALK_DOWN_1;
extern const CatFrame CAT_FRAME_WALK_DOWN_2;
extern const CatFrame CAT_FRAME_WALK_DOWN_3;
extern const CatFrame CAT_FRAME_WALK_UP_0;
extern const CatFrame CAT_FRAME_WALK_UP_1;
extern const CatFrame CAT_FRAME_WALK_UP_2;
extern const CatFrame CAT_FRAME_WALK_UP_3;
extern const CatFrame CAT_FRAME_WALK_RIGHT_DOWN_0;
extern const CatFrame CAT_FRAME_WALK_RIGHT_DOWN_1;
extern const CatFrame CAT_FRAME_WALK_RIGHT_DOWN_2;
extern const CatFrame CAT_FRAME_WALK_RIGHT_DOWN_3;
extern const CatFrame CAT_FRAME_WALK_LEFT_DOWN_0;
extern const CatFrame CAT_FRAME_WALK_LEFT_DOWN_1;
extern const CatFrame CAT_FRAME_WALK_LEFT_DOWN_2;
extern const CatFrame CAT_FRAME_WALK_LEFT_DOWN_3;
extern const CatFrame CAT_FRAME_WALK_RIGHT_UP_0;
extern const CatFrame CAT_FRAME_WALK_RIGHT_UP_1;
extern const CatFrame CAT_FRAME_WALK_RIGHT_UP_2;
extern const CatFrame CAT_FRAME_WALK_RIGHT_UP_3;
extern const CatFrame CAT_FRAME_WALK_LEFT_UP_0;
extern const CatFrame CAT_FRAME_WALK_LEFT_UP_1;
extern const CatFrame CAT_FRAME_WALK_LEFT_UP_2;
extern const CatFrame CAT_FRAME_WALK_LEFT_UP_3;
extern const CatFrame CAT_FRAME_SLEEP_1_LEFT_0;
extern const CatFrame CAT_FRAME_SLEEP_1_LEFT_1;
extern const CatFrame CAT_FRAME_SLEEP_1_RIGHT_0;
extern const CatFrame CAT_FRAME_SLEEP_1_RIGHT_1;
extern const CatFrame CAT_FRAME_SLEEP_2_LEFT_0;
extern const CatFrame CAT_FRAME_SLEEP_2_LEFT_1;
extern const CatFrame CAT_FRAME_SLEEP_2_RIGHT_0;
extern const CatFrame CAT_FRAME_SLEEP_2_RIGHT_1;
extern const CatFrame CAT_FRAME_SLEEP_3_LEFT_0;
extern const CatFrame CAT_FRAME_SLEEP_3_LEFT_1;
extern const CatFrame CAT_FRAME_SLEEP_3_RIGHT_0;
extern const CatFrame CAT_FRAME_SLEEP_3_RIGHT_1;
extern const CatFrame CAT_FRAME_SLEEP_4_LEFT_0;
extern const CatFrame CAT_FRAME_SLEEP_4_LEFT_1;
extern const CatFrame CAT_FRAME_SLEEP_4_RIGHT_0;
extern const CatFrame CAT_FRAME_SLEEP_4_RIGHT_1;
