#include "cat_seqs.h"

static const CatFrame* const _f_WALK_DOWN[] = { &CAT_FRAME_WALK_DOWN_0, &CAT_FRAME_WALK_DOWN_1, &CAT_FRAME_WALK_DOWN_2, &CAT_FRAME_WALK_DOWN_3 };
const CatSeq SEQ_WALK_DOWN = { _f_WALK_DOWN, 4 };

static const CatFrame* const _f_WALK_UP[] = { &CAT_FRAME_WALK_UP_0, &CAT_FRAME_WALK_UP_1, &CAT_FRAME_WALK_UP_2, &CAT_FRAME_WALK_UP_3 };
const CatSeq SEQ_WALK_UP = { _f_WALK_UP, 4 };

static const CatFrame* const _f_WALK_RIGHT[] = { &CAT_FRAME_WALK_RIGHT_0, &CAT_FRAME_WALK_RIGHT_1, &CAT_FRAME_WALK_RIGHT_2, &CAT_FRAME_WALK_RIGHT_3, &CAT_FRAME_WALK_RIGHT_4, &CAT_FRAME_WALK_RIGHT_5, &CAT_FRAME_WALK_RIGHT_6, &CAT_FRAME_WALK_RIGHT_7 };
const CatSeq SEQ_WALK_RIGHT = { _f_WALK_RIGHT, 8 };

static const CatFrame* const _f_WALK_LEFT[] = { &CAT_FRAME_WALK_LEFT_0, &CAT_FRAME_WALK_LEFT_1, &CAT_FRAME_WALK_LEFT_2, &CAT_FRAME_WALK_LEFT_3, &CAT_FRAME_WALK_LEFT_4, &CAT_FRAME_WALK_LEFT_5, &CAT_FRAME_WALK_LEFT_6, &CAT_FRAME_WALK_LEFT_7 };
const CatSeq SEQ_WALK_LEFT = { _f_WALK_LEFT, 8 };

static const CatFrame* const _f_WALK_DOWN_LEFT[] = { &CAT_FRAME_WALK_DOWN_LEFT_0, &CAT_FRAME_WALK_DOWN_LEFT_1, &CAT_FRAME_WALK_DOWN_LEFT_2, &CAT_FRAME_WALK_DOWN_LEFT_3, &CAT_FRAME_WALK_DOWN_LEFT_4, &CAT_FRAME_WALK_DOWN_LEFT_5 };
const CatSeq SEQ_WALK_DOWN_LEFT = { _f_WALK_DOWN_LEFT, 6 };

static const CatFrame* const _f_WALK_DOWN_RIGHT[] = { &CAT_FRAME_WALK_DOWN_RIGHT_0, &CAT_FRAME_WALK_DOWN_RIGHT_1, &CAT_FRAME_WALK_DOWN_RIGHT_2, &CAT_FRAME_WALK_DOWN_RIGHT_3, &CAT_FRAME_WALK_DOWN_RIGHT_4, &CAT_FRAME_WALK_DOWN_RIGHT_5 };
const CatSeq SEQ_WALK_DOWN_RIGHT = { _f_WALK_DOWN_RIGHT, 6 };

static const CatFrame* const _f_WALK_UP_RIGHT[] = { &CAT_FRAME_WALK_UP_RIGHT_0, &CAT_FRAME_WALK_UP_RIGHT_1, &CAT_FRAME_WALK_UP_RIGHT_2, &CAT_FRAME_WALK_UP_RIGHT_3, &CAT_FRAME_WALK_UP_RIGHT_4, &CAT_FRAME_WALK_UP_RIGHT_5 };
const CatSeq SEQ_WALK_UP_RIGHT = { _f_WALK_UP_RIGHT, 6 };

static const CatFrame* const _f_WALK_UP_LEFT[] = { &CAT_FRAME_WALK_UP_LEFT_0, &CAT_FRAME_WALK_UP_LEFT_1, &CAT_FRAME_WALK_UP_LEFT_2, &CAT_FRAME_WALK_UP_LEFT_3, &CAT_FRAME_WALK_UP_LEFT_4, &CAT_FRAME_WALK_UP_LEFT_5 };
const CatSeq SEQ_WALK_UP_LEFT = { _f_WALK_UP_LEFT, 6 };

static const CatFrame* const _f_REST_1[] = { &CAT_FRAME_REST_1_0, &CAT_FRAME_REST_1_1, &CAT_FRAME_REST_1_2, &CAT_FRAME_REST_1_3, &CAT_FRAME_REST_1_4, &CAT_FRAME_REST_1_5 };
const CatSeq SEQ_REST_1 = { _f_REST_1, 6 };

static const CatFrame* const _f_REST_2[] = { &CAT_FRAME_REST_2_0, &CAT_FRAME_REST_2_1, &CAT_FRAME_REST_2_2, &CAT_FRAME_REST_2_3, &CAT_FRAME_REST_2_4, &CAT_FRAME_REST_2_5, &CAT_FRAME_REST_2_6, &CAT_FRAME_REST_2_7 };
const CatSeq SEQ_REST_2 = { _f_REST_2, 8 };

static const CatFrame* const _f_REST_3[] = { &CAT_FRAME_REST_3_0, &CAT_FRAME_REST_3_1, &CAT_FRAME_REST_3_2, &CAT_FRAME_REST_3_3, &CAT_FRAME_REST_3_4, &CAT_FRAME_REST_3_5 };
const CatSeq SEQ_REST_3 = { _f_REST_3, 6 };

static const CatFrame* const _f_REST_4[] = { &CAT_FRAME_REST_4_0, &CAT_FRAME_REST_4_1, &CAT_FRAME_REST_4_2, &CAT_FRAME_REST_4_3, &CAT_FRAME_REST_4_4, &CAT_FRAME_REST_4_5, &CAT_FRAME_REST_4_6, &CAT_FRAME_REST_4_7, &CAT_FRAME_REST_4_8, &CAT_FRAME_REST_4_9 };
const CatSeq SEQ_REST_4 = { _f_REST_4, 10 };

static const CatFrame* const _f_SLEEP_1_L[] = { &CAT_FRAME_SLEEP_1_L_0, &CAT_FRAME_SLEEP_1_L_1 };
const CatSeq SEQ_SLEEP_1_L = { _f_SLEEP_1_L, 2 };

static const CatFrame* const _f_SLEEP_1_R[] = { &CAT_FRAME_SLEEP_1_R_0, &CAT_FRAME_SLEEP_1_R_1 };
const CatSeq SEQ_SLEEP_1_R = { _f_SLEEP_1_R, 2 };

static const CatFrame* const _f_SLEEP_2_L[] = { &CAT_FRAME_SLEEP_2_L_0, &CAT_FRAME_SLEEP_2_L_1 };
const CatSeq SEQ_SLEEP_2_L = { _f_SLEEP_2_L, 2 };

static const CatFrame* const _f_SLEEP_2_R[] = { &CAT_FRAME_SLEEP_2_R_0, &CAT_FRAME_SLEEP_2_R_1 };
const CatSeq SEQ_SLEEP_2_R = { _f_SLEEP_2_R, 2 };

static const CatFrame* const _f_SLEEP_3_L[] = { &CAT_FRAME_SLEEP_3_L_0, &CAT_FRAME_SLEEP_3_L_1 };
const CatSeq SEQ_SLEEP_3_L = { _f_SLEEP_3_L, 2 };

static const CatFrame* const _f_SLEEP_3_R[] = { &CAT_FRAME_SLEEP_3_R_0, &CAT_FRAME_SLEEP_3_R_1 };
const CatSeq SEQ_SLEEP_3_R = { _f_SLEEP_3_R, 2 };

static const CatFrame* const _f_SLEEP_4_L[] = { &CAT_FRAME_SLEEP_4_L_0, &CAT_FRAME_SLEEP_4_L_1 };
const CatSeq SEQ_SLEEP_4_L = { _f_SLEEP_4_L, 2 };

static const CatFrame* const _f_SLEEP_4_R[] = { &CAT_FRAME_SLEEP_4_R_0, &CAT_FRAME_SLEEP_4_R_1 };
const CatSeq SEQ_SLEEP_4_R = { _f_SLEEP_4_R, 2 };

static const CatFrame* const _f_EAT_DOWN[] = { &CAT_FRAME_EAT_DOWN_0, &CAT_FRAME_EAT_DOWN_1, &CAT_FRAME_EAT_DOWN_2, &CAT_FRAME_EAT_DOWN_3, &CAT_FRAME_EAT_DOWN_4, &CAT_FRAME_EAT_DOWN_5, &CAT_FRAME_EAT_DOWN_6, &CAT_FRAME_EAT_DOWN_7 };
const CatSeq SEQ_EAT_DOWN = { _f_EAT_DOWN, 8 };

static const CatFrame* const _f_EAT_UP[] = { &CAT_FRAME_EAT_UP_0, &CAT_FRAME_EAT_UP_1, &CAT_FRAME_EAT_UP_2, &CAT_FRAME_EAT_UP_3, &CAT_FRAME_EAT_UP_4, &CAT_FRAME_EAT_UP_5, &CAT_FRAME_EAT_UP_6, &CAT_FRAME_EAT_UP_7 };
const CatSeq SEQ_EAT_UP = { _f_EAT_UP, 8 };

static const CatFrame* const _f_EAT_LEFT[] = { &CAT_FRAME_EAT_LEFT_0, &CAT_FRAME_EAT_LEFT_1, &CAT_FRAME_EAT_LEFT_2, &CAT_FRAME_EAT_LEFT_3, &CAT_FRAME_EAT_LEFT_4, &CAT_FRAME_EAT_LEFT_5, &CAT_FRAME_EAT_LEFT_6, &CAT_FRAME_EAT_LEFT_7 };
const CatSeq SEQ_EAT_LEFT = { _f_EAT_LEFT, 8 };

static const CatFrame* const _f_EAT_RIGHT[] = { &CAT_FRAME_EAT_RIGHT_0, &CAT_FRAME_EAT_RIGHT_1, &CAT_FRAME_EAT_RIGHT_2, &CAT_FRAME_EAT_RIGHT_3, &CAT_FRAME_EAT_RIGHT_4, &CAT_FRAME_EAT_RIGHT_5, &CAT_FRAME_EAT_RIGHT_6, &CAT_FRAME_EAT_RIGHT_7 };
const CatSeq SEQ_EAT_RIGHT = { _f_EAT_RIGHT, 8 };

static const CatFrame* const _f_EAT_DOWN_RIGHT[] = { &CAT_FRAME_EAT_DOWN_RIGHT_0, &CAT_FRAME_EAT_DOWN_RIGHT_1, &CAT_FRAME_EAT_DOWN_RIGHT_2, &CAT_FRAME_EAT_DOWN_RIGHT_3, &CAT_FRAME_EAT_DOWN_RIGHT_4, &CAT_FRAME_EAT_DOWN_RIGHT_5, &CAT_FRAME_EAT_DOWN_RIGHT_6, &CAT_FRAME_EAT_DOWN_RIGHT_7 };
const CatSeq SEQ_EAT_DOWN_RIGHT = { _f_EAT_DOWN_RIGHT, 8 };

static const CatFrame* const _f_EAT_DOWN_LEFT[] = { &CAT_FRAME_EAT_DOWN_LEFT_0, &CAT_FRAME_EAT_DOWN_LEFT_1, &CAT_FRAME_EAT_DOWN_LEFT_2, &CAT_FRAME_EAT_DOWN_LEFT_3, &CAT_FRAME_EAT_DOWN_LEFT_4, &CAT_FRAME_EAT_DOWN_LEFT_5, &CAT_FRAME_EAT_DOWN_LEFT_6, &CAT_FRAME_EAT_DOWN_LEFT_7 };
const CatSeq SEQ_EAT_DOWN_LEFT = { _f_EAT_DOWN_LEFT, 8 };

static const CatFrame* const _f_EAT_UP_RIGHT[] = { &CAT_FRAME_EAT_UP_RIGHT_0, &CAT_FRAME_EAT_UP_RIGHT_1, &CAT_FRAME_EAT_UP_RIGHT_2, &CAT_FRAME_EAT_UP_RIGHT_3, &CAT_FRAME_EAT_UP_RIGHT_4, &CAT_FRAME_EAT_UP_RIGHT_5, &CAT_FRAME_EAT_UP_RIGHT_6, &CAT_FRAME_EAT_UP_RIGHT_7 };
const CatSeq SEQ_EAT_UP_RIGHT = { _f_EAT_UP_RIGHT, 8 };

static const CatFrame* const _f_EAT_UP_LEFT[] = { &CAT_FRAME_EAT_UP_LEFT_0, &CAT_FRAME_EAT_UP_LEFT_1, &CAT_FRAME_EAT_UP_LEFT_2, &CAT_FRAME_EAT_UP_LEFT_3, &CAT_FRAME_EAT_UP_LEFT_4, &CAT_FRAME_EAT_UP_LEFT_5, &CAT_FRAME_EAT_UP_LEFT_6, &CAT_FRAME_EAT_UP_LEFT_7 };
const CatSeq SEQ_EAT_UP_LEFT = { _f_EAT_UP_LEFT, 8 };

static const CatFrame* const _f_MEOW_SIT[] = { &CAT_FRAME_MEOW_SIT_0, &CAT_FRAME_MEOW_SIT_1, &CAT_FRAME_MEOW_SIT_2 };
const CatSeq SEQ_MEOW_SIT = { _f_MEOW_SIT, 3 };

static const CatFrame* const _f_MEOW_STAND[] = { &CAT_FRAME_MEOW_STAND_0, &CAT_FRAME_MEOW_STAND_1, &CAT_FRAME_MEOW_STAND_2 };
const CatSeq SEQ_MEOW_STAND = { _f_MEOW_STAND, 3 };

static const CatFrame* const _f_MEOW_SIT_2[] = { &CAT_FRAME_MEOW_SIT_2_0, &CAT_FRAME_MEOW_SIT_2_1, &CAT_FRAME_MEOW_SIT_2_2 };
const CatSeq SEQ_MEOW_SIT_2 = { _f_MEOW_SIT_2, 3 };

static const CatFrame* const _f_MEOW_LIE[] = { &CAT_FRAME_MEOW_LIE_0, &CAT_FRAME_MEOW_LIE_1, &CAT_FRAME_MEOW_LIE_2 };
const CatSeq SEQ_MEOW_LIE = { _f_MEOW_LIE, 3 };

static const CatFrame* const _f_YAWN_SIT[] = { &CAT_FRAME_YAWN_SIT_0, &CAT_FRAME_YAWN_SIT_1, &CAT_FRAME_YAWN_SIT_2, &CAT_FRAME_YAWN_SIT_3, &CAT_FRAME_YAWN_SIT_4, &CAT_FRAME_YAWN_SIT_5, &CAT_FRAME_YAWN_SIT_6, &CAT_FRAME_YAWN_SIT_7 };
const CatSeq SEQ_YAWN_SIT = { _f_YAWN_SIT, 8 };

static const CatFrame* const _f_YAWN_STAND[] = { &CAT_FRAME_YAWN_STAND_0, &CAT_FRAME_YAWN_STAND_1, &CAT_FRAME_YAWN_STAND_2, &CAT_FRAME_YAWN_STAND_3, &CAT_FRAME_YAWN_STAND_4, &CAT_FRAME_YAWN_STAND_5, &CAT_FRAME_YAWN_STAND_6, &CAT_FRAME_YAWN_STAND_7 };
const CatSeq SEQ_YAWN_STAND = { _f_YAWN_STAND, 8 };

static const CatFrame* const _f_YAWN_SIT_2[] = { &CAT_FRAME_YAWN_SIT_2_0, &CAT_FRAME_YAWN_SIT_2_1, &CAT_FRAME_YAWN_SIT_2_2, &CAT_FRAME_YAWN_SIT_2_3, &CAT_FRAME_YAWN_SIT_2_4, &CAT_FRAME_YAWN_SIT_2_5, &CAT_FRAME_YAWN_SIT_2_6, &CAT_FRAME_YAWN_SIT_2_7 };
const CatSeq SEQ_YAWN_SIT_2 = { _f_YAWN_SIT_2, 8 };

static const CatFrame* const _f_YAWN_LIE[] = { &CAT_FRAME_YAWN_LIE_0, &CAT_FRAME_YAWN_LIE_1, &CAT_FRAME_YAWN_LIE_2, &CAT_FRAME_YAWN_LIE_3, &CAT_FRAME_YAWN_LIE_4, &CAT_FRAME_YAWN_LIE_5, &CAT_FRAME_YAWN_LIE_6, &CAT_FRAME_YAWN_LIE_7 };
const CatSeq SEQ_YAWN_LIE = { _f_YAWN_LIE, 8 };

static const CatFrame* const _f_WASH_SIT[] = { &CAT_FRAME_WASH_SIT_0, &CAT_FRAME_WASH_SIT_1, &CAT_FRAME_WASH_SIT_2, &CAT_FRAME_WASH_SIT_3, &CAT_FRAME_WASH_SIT_4, &CAT_FRAME_WASH_SIT_5, &CAT_FRAME_WASH_SIT_6, &CAT_FRAME_WASH_SIT_7, &CAT_FRAME_WASH_SIT_8 };
const CatSeq SEQ_WASH_SIT = { _f_WASH_SIT, 9 };

static const CatFrame* const _f_WASH_STAND[] = { &CAT_FRAME_WASH_STAND_0, &CAT_FRAME_WASH_STAND_1, &CAT_FRAME_WASH_STAND_2, &CAT_FRAME_WASH_STAND_3, &CAT_FRAME_WASH_STAND_4, &CAT_FRAME_WASH_STAND_5, &CAT_FRAME_WASH_STAND_6, &CAT_FRAME_WASH_STAND_7, &CAT_FRAME_WASH_STAND_8 };
const CatSeq SEQ_WASH_STAND = { _f_WASH_STAND, 9 };

static const CatFrame* const _f_WASH_LIE[] = { &CAT_FRAME_WASH_LIE_0, &CAT_FRAME_WASH_LIE_1, &CAT_FRAME_WASH_LIE_2, &CAT_FRAME_WASH_LIE_3, &CAT_FRAME_WASH_LIE_4, &CAT_FRAME_WASH_LIE_5, &CAT_FRAME_WASH_LIE_6 };
const CatSeq SEQ_WASH_LIE = { _f_WASH_LIE, 7 };

static const CatFrame* const _f_SCRATCH_L[] = { &CAT_FRAME_SCRATCH_L_0, &CAT_FRAME_SCRATCH_L_1, &CAT_FRAME_SCRATCH_L_2, &CAT_FRAME_SCRATCH_L_3, &CAT_FRAME_SCRATCH_L_4, &CAT_FRAME_SCRATCH_L_5, &CAT_FRAME_SCRATCH_L_6, &CAT_FRAME_SCRATCH_L_7, &CAT_FRAME_SCRATCH_L_8, &CAT_FRAME_SCRATCH_L_9, &CAT_FRAME_SCRATCH_L_10 };
const CatSeq SEQ_SCRATCH_L = { _f_SCRATCH_L, 11 };

static const CatFrame* const _f_SCRATCH_R[] = { &CAT_FRAME_SCRATCH_R_0, &CAT_FRAME_SCRATCH_R_1, &CAT_FRAME_SCRATCH_R_2, &CAT_FRAME_SCRATCH_R_3, &CAT_FRAME_SCRATCH_R_4, &CAT_FRAME_SCRATCH_R_5, &CAT_FRAME_SCRATCH_R_6, &CAT_FRAME_SCRATCH_R_7, &CAT_FRAME_SCRATCH_R_8, &CAT_FRAME_SCRATCH_R_9, &CAT_FRAME_SCRATCH_R_10 };
const CatSeq SEQ_SCRATCH_R = { _f_SCRATCH_R, 11 };

static const CatFrame* const _f_HISS_L[] = { &CAT_FRAME_HISS_L_0, &CAT_FRAME_HISS_L_1 };
const CatSeq SEQ_HISS_L = { _f_HISS_L, 2 };

static const CatFrame* const _f_HISS_R[] = { &CAT_FRAME_HISS_R_0, &CAT_FRAME_HISS_R_1 };
const CatSeq SEQ_HISS_R = { _f_HISS_R, 2 };

static const CatFrame* const _f_ATTACK_READY[] = { &CAT_FRAME_ATTACK_READY_0 };
const CatSeq SEQ_ATTACK_READY = { _f_ATTACK_READY, 1 };

static const CatFrame* const _f_PAW_DOWN[] = { &CAT_FRAME_PAW_DOWN_0, &CAT_FRAME_PAW_DOWN_1, &CAT_FRAME_PAW_DOWN_2, &CAT_FRAME_PAW_DOWN_3, &CAT_FRAME_PAW_DOWN_4, &CAT_FRAME_PAW_DOWN_5, &CAT_FRAME_PAW_DOWN_6, &CAT_FRAME_PAW_DOWN_7, &CAT_FRAME_PAW_DOWN_8 };
const CatSeq SEQ_PAW_DOWN = { _f_PAW_DOWN, 9 };

static const CatFrame* const _f_PAW_UP[] = { &CAT_FRAME_PAW_UP_0, &CAT_FRAME_PAW_UP_1, &CAT_FRAME_PAW_UP_2, &CAT_FRAME_PAW_UP_3, &CAT_FRAME_PAW_UP_4 };
const CatSeq SEQ_PAW_UP = { _f_PAW_UP, 5 };

static const CatFrame* const _f_PAW_LEFT[] = { &CAT_FRAME_PAW_LEFT_0, &CAT_FRAME_PAW_LEFT_1, &CAT_FRAME_PAW_LEFT_2, &CAT_FRAME_PAW_LEFT_3, &CAT_FRAME_PAW_LEFT_4, &CAT_FRAME_PAW_LEFT_5, &CAT_FRAME_PAW_LEFT_6 };
const CatSeq SEQ_PAW_LEFT = { _f_PAW_LEFT, 7 };

static const CatFrame* const _f_PAW_RIGHT[] = { &CAT_FRAME_PAW_RIGHT_0, &CAT_FRAME_PAW_RIGHT_1, &CAT_FRAME_PAW_RIGHT_2, &CAT_FRAME_PAW_RIGHT_3, &CAT_FRAME_PAW_RIGHT_4, &CAT_FRAME_PAW_RIGHT_5, &CAT_FRAME_PAW_RIGHT_6 };
const CatSeq SEQ_PAW_RIGHT = { _f_PAW_RIGHT, 7 };

static const CatFrame* const _f_PAW_DOWN_RIGHT[] = { &CAT_FRAME_PAW_DOWN_RIGHT_0, &CAT_FRAME_PAW_DOWN_RIGHT_1, &CAT_FRAME_PAW_DOWN_RIGHT_2, &CAT_FRAME_PAW_DOWN_RIGHT_3, &CAT_FRAME_PAW_DOWN_RIGHT_4, &CAT_FRAME_PAW_DOWN_RIGHT_5, &CAT_FRAME_PAW_DOWN_RIGHT_6, &CAT_FRAME_PAW_DOWN_RIGHT_7, &CAT_FRAME_PAW_DOWN_RIGHT_8 };
const CatSeq SEQ_PAW_DOWN_RIGHT = { _f_PAW_DOWN_RIGHT, 9 };

static const CatFrame* const _f_PAW_DOWN_LEFT[] = { &CAT_FRAME_PAW_DOWN_LEFT_0, &CAT_FRAME_PAW_DOWN_LEFT_1, &CAT_FRAME_PAW_DOWN_LEFT_2, &CAT_FRAME_PAW_DOWN_LEFT_3, &CAT_FRAME_PAW_DOWN_LEFT_4, &CAT_FRAME_PAW_DOWN_LEFT_5, &CAT_FRAME_PAW_DOWN_LEFT_6, &CAT_FRAME_PAW_DOWN_LEFT_7, &CAT_FRAME_PAW_DOWN_LEFT_8 };
const CatSeq SEQ_PAW_DOWN_LEFT = { _f_PAW_DOWN_LEFT, 9 };

static const CatFrame* const _f_PAW_UP_RIGHT[] = { &CAT_FRAME_PAW_UP_RIGHT_0, &CAT_FRAME_PAW_UP_RIGHT_1, &CAT_FRAME_PAW_UP_RIGHT_2, &CAT_FRAME_PAW_UP_RIGHT_3, &CAT_FRAME_PAW_UP_RIGHT_4 };
const CatSeq SEQ_PAW_UP_RIGHT = { _f_PAW_UP_RIGHT, 5 };

static const CatFrame* const _f_PAW_UP_LEFT[] = { &CAT_FRAME_PAW_UP_LEFT_0, &CAT_FRAME_PAW_UP_LEFT_1, &CAT_FRAME_PAW_UP_LEFT_2, &CAT_FRAME_PAW_UP_LEFT_3, &CAT_FRAME_PAW_UP_LEFT_4 };
const CatSeq SEQ_PAW_UP_LEFT = { _f_PAW_UP_LEFT, 5 };

static const CatFrame* const _f_HIND[] = { &CAT_FRAME_HIND_0, &CAT_FRAME_HIND_1, &CAT_FRAME_HIND_2, &CAT_FRAME_HIND_3 };
const CatSeq SEQ_HIND = { _f_HIND, 4 };

// Walk direction table: DOWN=0 UP=1 RIGHT=2 LEFT=3 DL=4 DR=5 UR=6 UL=7
const CatSeq* const WALK_SEQ[8] = {
  &SEQ_WALK_DOWN, &SEQ_WALK_UP, &SEQ_WALK_RIGHT, &SEQ_WALK_LEFT,
  &SEQ_WALK_DOWN_LEFT, &SEQ_WALK_DOWN_RIGHT, &SEQ_WALK_UP_RIGHT, &SEQ_WALK_UP_LEFT
};

const CatSeq* const EAT_SEQ[8] = {
  &SEQ_EAT_DOWN, &SEQ_EAT_UP, &SEQ_EAT_RIGHT, &SEQ_EAT_LEFT,
  &SEQ_EAT_DOWN_LEFT, &SEQ_EAT_DOWN_RIGHT, &SEQ_EAT_UP_RIGHT, &SEQ_EAT_UP_LEFT
};

const CatSeq* const PAW_SEQ[8] = {
  &SEQ_PAW_DOWN, &SEQ_PAW_UP, &SEQ_PAW_RIGHT, &SEQ_PAW_LEFT,
  &SEQ_PAW_DOWN_LEFT, &SEQ_PAW_DOWN_RIGHT, &SEQ_PAW_UP_RIGHT, &SEQ_PAW_UP_LEFT
};

const CatSeq* const SLEEP_SEQ[8] = {
  &SEQ_SLEEP_1_L, &SEQ_SLEEP_1_R, &SEQ_SLEEP_2_L, &SEQ_SLEEP_2_R,
  &SEQ_SLEEP_3_L, &SEQ_SLEEP_3_R, &SEQ_SLEEP_4_L, &SEQ_SLEEP_4_R
};
