#pragma once
// AUTO-GENERATED by tools/convert_grass_bg.py — do not edit.
#include <Arduino.h>

#define GRASS_BG_W 368
#define GRASS_BG_H 448

// PROGMEM RGB565 array, row-major, (GRASS_BG_W * GRASS_BG_H) entries.
extern const uint16_t GRASS_BG[] PROGMEM;
