#!/usr/bin/env python3
"""
convert_cat_assets.py
Convert a sprite-sheet PNG into C++ PROGMEM arrays for ESP32 / Arduino_GFX.

Usage:
  python tools/convert_cat_assets.py \
      --input  "raw_assets/Free pack/cat 1.png" \
      --slot   32 \
      --cols   11 \
      --output src/assets/cat_frames

The script slices the sheet into (slot × slot) cells, converts each pixel to
RGB565, builds a 1-byte-per-pixel alpha mask (1=draw, 0=transparent), and
writes cat_frames.h + cat_frames.cpp.
"""

import argparse
import csv
from pathlib import Path
from PIL import Image

# ── Frame manifest ────────────────────────────────────────────────────────────
# (name, row, col)  — adjust as you discover what each slot contains.
# Use tools/preview_cat_slots.py to view the grid before editing this list.
DEFAULT_FRAMES = [
    ("TEST_0", 0, 0),
    ("TEST_1", 0, 1),
    ("TEST_2", 0, 2),
    ("TEST_3", 0, 3),
]


def load_manifest(csv_path: str) -> list[tuple[str, int, int]]:
    """Load frame list from a CSV manifest (skips comment lines starting with #)."""
    frames = []
    with open(csv_path, newline="") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = [p.strip() for p in line.split(",")]
            if len(parts) < 3:
                continue
            name, row, col = parts[0].upper(), int(parts[1]), int(parts[2])
            frames.append((name, row, col))
    return frames

ALPHA_THRESHOLD = 20   # alpha <= this → transparent pixel


def to_rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def extract_frame(img: Image.Image, row: int, col: int, slot: int):
    """Return (pixels_rgb565, mask_uint8) for one slot cell."""
    x0, y0 = col * slot, row * slot
    cell = img.crop((x0, y0, x0 + slot, y0 + slot))
    rgba = cell.convert("RGBA")

    pixels, mask = [], []
    for py in range(slot):
        for px in range(slot):
            r, g, b, a = rgba.getpixel((px, py))
            pixels.append(to_rgb565(r, g, b))
            mask.append(1 if a > ALPHA_THRESHOLD else 0)
    return pixels, mask


def format_array_u16(name: str, data: list[int]) -> str:
    hex_vals = [f"0x{v:04X}" for v in data]
    rows = [", ".join(hex_vals[i:i+16]) for i in range(0, len(hex_vals), 16)]
    body = ",\n  ".join(rows)
    return f"const uint16_t {name}[] PROGMEM = {{\n  {body}\n}};"


def format_array_u8(name: str, data: list[int]) -> str:
    rows = [", ".join(str(v) for v in data[i:i+32]) for i in range(0, len(data), 32)]
    body = ",\n  ".join(rows)
    return f"const uint8_t {name}[] PROGMEM = {{\n  {body}\n}};"


def generate(input_path: str, slot: int, cols: int, output_base: str,
             frames: list[tuple[str, int, int]]) -> None:
    img = Image.open(input_path).convert("RGBA")
    w, h = img.size
    rows_total = h // slot
    print(f"Sheet: {w}×{h}  →  {cols} cols × {rows_total} rows  (slot={slot})")

    # Validate requested frames
    for name, row, col in frames:
        if row >= rows_total or col >= cols:
            raise ValueError(f"Frame {name} ({row},{col}) out of range "
                             f"({rows_total} rows, {cols} cols)")

    out_h   = Path(output_base).with_suffix(".h")
    out_cpp = Path(output_base).with_suffix(".cpp")

    # ── .h ───────────────────────────────────────────────────────────────────
    extern_decls = "\n".join(
        f"extern const CatFrame CAT_FRAME_{name};" for name, *_ in frames
    )
    header = (
        "#pragma once\n"
        "// AUTO-GENERATED by tools/convert_cat_assets.py — do not edit by hand.\n"
        "#include <Arduino.h>\n"
        "\n"
        f"#define CAT_FRAME_W {slot}\n"
        f"#define CAT_FRAME_H {slot}\n"
        "\n"
        "struct CatFrame {\n"
        "    const uint16_t* pixels; // RGB565, row-major, PROGMEM\n"
        "    const uint8_t*  mask;   // 1=draw, 0=transparent, PROGMEM\n"
        "    uint16_t        width;\n"
        "    uint16_t        height;\n"
        "};\n"
        "\n"
        + extern_decls + "\n"
    )
    out_h.write_text(header)
    print(f"Written: {out_h}")

    # ── .cpp ─────────────────────────────────────────────────────────────────
    cpp_parts = [
        f'#include "{out_h.name}"',
        "",
    ]
    for name, row, col in frames:
        pixels, mask_data = extract_frame(img, row, col, slot)
        px_name   = f"CAT_{name}_PIXELS"
        mask_name = f"CAT_{name}_MASK"

        cpp_parts.append(f"// row={row}, col={col}")
        cpp_parts.append(format_array_u16(px_name, pixels))
        cpp_parts.append(format_array_u8(mask_name, mask_data))
        cpp_parts.append(
            f"const CatFrame CAT_FRAME_{name} = {{"
            f" {px_name}, {mask_name}, {slot}, {slot} }};"
        )
        cpp_parts.append("")

        opaque = sum(mask_data)
        print(f"  {name:12s} (r{row},c{col})  {opaque}/{slot*slot} opaque pixels")

    out_cpp.write_text("\n".join(cpp_parts) + "\n")
    print(f"Written: {out_cpp}")


def parse_frame_spec(s: str) -> tuple[str, int, int]:
    """Parse 'NAME:row,col' into (name, row, col)."""
    name, coords = s.split(":")
    row, col = coords.split(",")
    return name.upper(), int(row), int(col)


def main():
    ap = argparse.ArgumentParser(description="PNG sprite-sheet → C++ PROGMEM arrays")
    ap.add_argument("--input",  required=True, help="Input PNG path")
    ap.add_argument("--slot",   type=int, default=32, help="Slot size in pixels (default 32)")
    ap.add_argument("--cols",   type=int, default=11, help="Columns in the sheet (default 11)")
    ap.add_argument("--output", required=True,
                    help="Output path base, e.g. src/assets/cat_frames")
    ap.add_argument("--frames", nargs="*", metavar="NAME:row,col",
                    help="Frames to export. Example: --frames IDLE_0:0,0 SLEEP_0:3,2")
    ap.add_argument("--manifest", metavar="CSV_PATH",
                    help="CSV manifest file (name,row,col — lines starting with # ignored). "
                         "Overrides --frames and DEFAULT_FRAMES.")
    args = ap.parse_args()

    frames = DEFAULT_FRAMES
    if args.manifest:
        frames = load_manifest(args.manifest)
    elif args.frames:
        # Support both "A:0,0;B:0,1" (single string) and A:0,0 B:0,1 (separate args)
        raw = ";".join(args.frames)
        parts = [p.strip() for p in raw.split(";") if p.strip()]
        frames = [parse_frame_spec(p) for p in parts]

    generate(args.input, args.slot, args.cols, args.output, frames)


if __name__ == "__main__":
    main()
