#!/usr/bin/env python3
"""
convert_grass_bg.py
Convert grass.jpg to a PROGMEM RGB565 C++ array for the SH8601 display.

Run from the project root:
    python3 tools/convert_grass_bg.py
"""

from PIL import Image
import os

SCREEN_W = 368
SCREEN_H = 448
INPUT    = "raw_assets/grass.jpg"
OUT_H    = "src/assets/grass_bg.h"
OUT_CPP  = "src/assets/grass_bg.cpp"


def to_rgb565(r: int, g: int, b: int) -> int:
    # Same formula as convert_cat_assets.py
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main():
    img = Image.open(INPUT).convert("RGB")
    img = img.resize((SCREEN_W, SCREEN_H), Image.LANCZOS)
    print(f"Resized to {img.size}")

    pixels = []
    for y in range(SCREEN_H):
        for x in range(SCREEN_W):
            r, g, b = img.getpixel((x, y))
            pixels.append(to_rgb565(r, g, b))

    total = len(pixels)
    print(f"Total pixels: {total}  ({total * 2} bytes)")

    # ── Header ────────────────────────────────────────────────────────────────
    with open(OUT_H, "w") as f:
        f.write("#pragma once\n")
        f.write("// AUTO-GENERATED by tools/convert_grass_bg.py — do not edit.\n")
        f.write("#include <Arduino.h>\n\n")
        f.write(f"#define GRASS_BG_W {SCREEN_W}\n")
        f.write(f"#define GRASS_BG_H {SCREEN_H}\n\n")
        f.write("// PROGMEM RGB565 array, row-major, (GRASS_BG_W * GRASS_BG_H) entries.\n")
        f.write("extern const uint16_t GRASS_BG[] PROGMEM;\n")

    # ── Source ────────────────────────────────────────────────────────────────
    PER_LINE = 16
    with open(OUT_CPP, "w") as f:
        f.write('#include "grass_bg.h"\n\n')
        f.write("// AUTO-GENERATED by tools/convert_grass_bg.py — do not edit.\n")
        f.write("const uint16_t GRASS_BG[] PROGMEM = {\n")

        for i in range(0, total, PER_LINE):
            chunk = pixels[i : i + PER_LINE]
            f.write("  " + ", ".join(f"0x{p:04X}" for p in chunk) + ",\n")

        f.write("};\n")

    print(f"Written: {OUT_H}")
    print(f"Written: {OUT_CPP}")


if __name__ == "__main__":
    main()
